### ISSUE TITLE
Waring in console when using chat command

### ISSUE THREAD

**Issue by MattA-Official** [software-inc-multiplayer/software-inc-multiplayer#16]
**Describe the bug**
Two warnings appear when you use the chat command

**To Reproduce**
Steps to reproduce the behaviour:
1. Press "New Game" and continue as if you'd start a normal game
2. Open the Console and write "MULTIPLAYER_START" (press enter)
3. Write "MULTIPLAYER_CHAT" inside the console (press enter)
4. The warnings appear

**Expected behaviour**
No warnings

**Screenshots**
![image](https://user-images.githubusercontent.com/43476212/90037225-dc39ec00-dcbb-11ea-99cf-283ab9bdedc2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Inc Version: Alpha 11.6.11
 - Mod Version: 0.2.2-unstable

**Comment by ghost** [comment]
This I probably because you haven't connected. Easy fix, check if the user is connected before running the chat command.

**Comment by ghost** [comment]
Run MULTIPLAYER_CONNECT before running chat

**Comment by MattA-Official** [comment]
I was following the instructions to test and told to report warnings as bugs.

**Comment by daredloco** [comment]
Thanks for your Issue.
I got the same error, it's because the Client will disconnect after some ms but I couldn't find out why.
I was hoping it has something to do with my firewall, but it seems like something inside the code is wrong.
It works fine inside the test environment (not Software Inc), I'll check it out maybe I'm missing something here.

You did it right MattA, MULTIPLAYER_START does connect you as a Host so this should work just fine

**Comment by daredloco** [comment]
I did replace the WatsonTcp library with the Telepathy library so this problem doesn't exist anymore.
Connections are tested and are working as expected with Telepathy!
