### ISSUE TITLE
Error disabling mod

### ISSUE THREAD

**Issue by Chik3r** [software-inc-multiplayer/software-inc-multiplayer#27]
**Describe the bug**
When deactivating the mod, it gives an error to the output_log.txt (no error on console)

**To Reproduce**
1. Enable mod
2. Disable mod
3. Get pop-up saying `Failed activating mod. Check log for details`
4. Check log (In SINC install dir)

**Expected behaviour**
No error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Inc Version: Alpha 11.6.11
 - Mod Version: v0.2.6-unstable
 
**Additional context**
Error:
```
Error activating/deactivating dll mod Multiplayer.Core:
System.NullReferenceException: Object reference not set to an instance of an object
  at Multiplayer.Core.GameBehaviour.OnDeactivate () [0x00007] in <27ce75c8901545708e16e458fe47b595>:0 
  at ModController+DLLMod.Activate (System.Boolean active) [0x00058] in <9ea9c027dc0040299fd0b91d02ca7bd1>:0 
  at OptionsWindow+<AddModOption>c__AnonStorey9.<>m__0 (System.Boolean x) [0x00000] in <9ea9c027dc0040299fd0b91d02ca7bd1>:0 
```

**Comment by Chik3r** [comment]
Also, it seems to only happen in the main menu. It doesn't happen while in a save

**Comment by daredloco** [comment]
Thank you for the Issue!
The problem happens because the "MPButton" only gets called if you did enter the mainscene but if you deactivate the mod it tries to call the MPButton.

I did add
```cs
if(MPButton != null)
                MPButton.gameObject.SetActive(false);
```

so it will only set active to false if the MPButton exists.

Thats the fix for it: https://github.com/cal3432/software-inc-multiplayer/commit/38f922338de43448f1461e2ec3d11dbded625b6a
