### ISSUE TITLE
MULTIPLAYER_SAVE could not load file Serialization

### ISSUE THREAD

**Issue by Chik3r** [software-inc-multiplayer/software-inc-multiplayer#28]
**Describe the bug**
When running the command `MULTIPLAYER_SAVE`, it gives the following error:
`Could not load file or assembly 'System_Runtime_Serialization, Culture—neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.`

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable mod
2. Start a server
3. Run `MULTIPLAYER_SAVE`

**Expected behaviour**
No Error

**Screenshots**
![image](https://user-images.githubusercontent.com/31808958/90694927-757e7a80-e247-11ea-948c-91ebb5469a59.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Inc Version: Alpha 11.6.11
 - Mod Version: v0.2.6-unstable

**Comment by daredloco** [comment]
Thank you for the Issue,
this is a known bug in this version as it still tries to save in JSON while it should save in anything more handy.
This bug is on my priority list and will be fixed within the next update.

Detail: It seems like there is a problem with SINC and any System.Serialization thing thats not within our own libraries, but we will use the same serialization that we use for the Network Messages (There was the same problem) so it should be fine.

Thanks again for the testing!

**Comment by ghost** [comment]
Fixed.
